In [1]:
# lab1
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print(iris_X[:2,:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]


In [3]:
print(iris_y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
X_train,X_test,y_train,y_test=train_test_split(iris_X,iris_y,test_size=0.3)

In [5]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
print(knn.predict(X_test))

[1 0 2 2 1 0 1 2 1 0 0 1 1 0 0 2 0 2 0 2 2 0 0 0 0 2 2 1 1 0 2 2 2 2 1 2 1
 0 1 1 1 0 2 1 1]


In [6]:
print(y_test)

[1 0 2 2 1 0 1 2 1 0 0 1 1 0 0 2 0 2 0 2 1 0 0 0 0 2 2 1 1 0 2 2 2 2 1 2 1
 0 1 1 1 0 1 1 2]


In [7]:
#lab2
from sklearn import datasets
from sklearn.linear_model import LinearRegression

In [8]:
loaded_data = datasets.load_boston()
data_X = loaded_data.data
data_y = loaded_data.target

model = LinearRegression()
model.fit(data_X,data_y)

print(model.predict(data_X[:4,:]))

[30.00384338 25.02556238 30.56759672 28.60703649]


In [9]:
print(data_y[:4])

[24.  21.6 34.7 33.4]


In [10]:
X,y = datasets.make_regression(n_samples=100,n_features = 1,n_targets=1,noise=10)

plt.figure()
plt.scatter(X,y)
plt.show()

<Figure size 640x480 with 1 Axes>

In [11]:
#lab3
from sklearn import preprocessing
import numpy as np
from sklearn.datasets.samples_generator import make_classification
from sklearn.svm import SVC

In [12]:
X,y = make_classification(n_samples=300,n_features=2,n_redundant=0,n_informative=2,
                         random_state=22,n_clusters_per_class=1,scale=100)
#X = preprocessing.scale(X)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
df=SVC()
df.fit(X_train,y_train)
print(df.score(X_test,y_test))

0.4888888888888889


D:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
