In [1]:
import numpy as np

In [2]:
x=np.empty([3,2],dtype=float)
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#列表变成ndarray
x=[1,2,3]
np.asarray(x)

array([1, 2, 3])

In [7]:
#根据范围创建array——numpy.arange(start, stop, step, dtype)
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
#生成等差数列
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.linspace(1,1,10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
#等比数列——np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
np.logspace(1.0,2.0,num=10 )

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [11]:
# Numpy切片与索引，与list一致
#Numpy 布尔索引
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x[x>5]  #挑选出大于5的元素

array([ 6,  7,  8,  9, 10, 11])

In [12]:
#过滤掉nan，用~
a = np.array([np.nan,1,2,np.nan,3,4,5])  
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [13]:
a = np.array([1,  2+6j,  5,  3.5+5j]) 
a[np.iscomplex(a)]

array([2. +6.j, 3.5+5.j])

In [14]:
#Numpy广播 若数组a,b的长度相同，即a.shape==b.shape,则a*b为对应数点乘
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
a * b 

array([ 10,  40,  90, 160])

In [15]:
'''广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式，
对数组的算术运算通常在相应的元素上进行。当运算中的 2 个数组的形状不
同时，numpy 将自动触发广播机制。'''
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [16]:
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度
a+bb

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [17]:
#numpy.reshape 在不改变数据的条件下修改形状
#ndarray.flatten(order='C')——展开数组。order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。
a.flatten()

array([ 0,  0,  0, 10, 10, 10, 20, 20, 20, 30, 30, 30])

In [18]:
#展平数组 np.ravel(a,order='C') order同上
np.ravel(a)

array([ 0,  0,  0, 10, 10, 10, 20, 20, 20, 30, 30, 30])

In [19]:
#翻转数组 np.transpose(a) , a.T
#交换数组的两个轴 np.swapaxes(a,axis1,axis2) 交换axis1轴维度交换到axis2维度
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
print (np.swapaxes(a, 2, 0))

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [21]:
#连接数组 numpy.concatenate((a1, a2, ...), axis)
#分割数组 numpy.split(ary, indices_or_sections, axis)
a = np.arange(9)
b = np.split(a,3) #分为三个大小相等的子数组
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [22]:
np.split(a,[4,7]) #在一维数组中表明的位置分割

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [23]:
#返回指定形状的新数组 np.resize(a,(3,3))
#将值添加到数组末尾 np.append(arr, values, axis=None)
#沿指定轴将值插入到指定下标之前 np.insert(arr, obj, values, axis) obj：在其之前插入值的索引
#删掉某个轴的子数组，并返回删除后的新数组 np.delete(arr, obj, axis)
#查找数组内的唯一元素 np.unique(arr, return_index, return_inverse, return_counts)
np.unique(np.array([5,2,6,2,7,5,6,8,2,9]))

array([2, 5, 6, 7, 8, 9])

In [24]:
#Numpy数学函数 np.sin()  np.cos()  np.tan()
#Numpy算数运算 np.add()  np.substract()  np.multiply()  np.divide()  加减乘除
#其他 numpy.power() numpy.mod()——对应元素相除后的余数
#统计函数：np.amin()  np.amax()
#numpy.ptp() 计算数组中元素最大值与最小值的差（最大值 - 最小值）。
np.ptp(a)

8

In [32]:
# np.median(arr) ——中位数
# np.mean(arr) ——算数平均值
# np.std(arr) ——标准差
# np.var(arr) ——方差
a = np.arange(3,3)
b = np.random.rand(3)

In [41]:
#numpy.where() 函数返回输入数组中满足给定条件的元素的索引。
y = np.where(x>5) #挑出大于5的元素的索引

In [45]:
y

(array([2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [46]:
x[y]

array([ 6,  7,  8,  9, 10, 11])

In [47]:
#Numpy矩阵库 线性代数函数库linalg
#np.dot(a,b) 数组点乘
#np.vdot(a,b) vdot 将数组展开计算内积
#np.matmul(a,b)  返回两个数组的矩阵乘积。
#np.linalg.det(a) 函数计算输入矩阵的行列式。
#numpy.linalg.inv(a) 计算矩阵的乘法逆矩阵。

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
x = np.matrix(x)
y = np.matrix(np.arange(3))

In [53]:
x

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [54]:
y

matrix([[0, 1, 2]])

In [56]:
np.multiply(x,y)

matrix([[ 0,  1,  4],
        [ 0,  4, 10],
        [ 0,  7, 16],
        [ 0, 10, 22]])